services:
  cassandra_0:
    container_name: 'cassandra-node0'
    image: 'cassandra:4.1.3'
    environment:
      CASSANDRA_SEEDS: 'cassandra-node1, cassandra-node2'
      CASSANDRA_CLUSTER_NAME: 'db_cluster'
      CASSANDRA_BROADCAST_RPC_ADDRESS: '127.0.0.1'
    ports:
      - 9042:9042
    networks:
      - cassandra
  cassandra_1:
    container_name: 'cassandra-node1'
    image: 'cassandra:4.1.3'
    environment:
      CASSANDRA_SEEDS: 'cassandra-node0, cassandra-node2'
      CASSANDRA_CLUSTER_NAME: 'db_cluster'
    ports:
      - 9043:9042
    networks:
      - cassandra
  cassandra_2:
    container_name: 'cassandra-node2'
    image: 'cassandra:4.1.3'
    environment:
      CASSANDRA_SEEDS: 'cassandra-node0, cassandra-node1'
      CASSANDRA_CLUSTER_NAME: 'db_cluster'
    ports:
      - 9044:9042
    networks:
      - cassandra
networks:
  cassandra:
    name: cassandra_network
    driver: bridge
